// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjejvECT5JXhiFL50jEdEPf9_9GiFulps',
    appId: '1:713380258131:web:7ea95072eca985a9ee41a6',
    messagingSenderId: '713380258131',
    projectId: 'wallpaper-1bd71',
    authDomain: 'wallpaper-1bd71.firebaseapp.com',
    storageBucket: 'wallpaper-1bd71.appspot.com',
    measurementId: 'G-X6PPRK29BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Lx9gLisVFbN50EbSHGK2THzhW4KLtF0',
    appId: '1:713380258131:android:3437b2b8c5adad5eee41a6',
    messagingSenderId: '713380258131',
    projectId: 'wallpaper-1bd71',
    storageBucket: 'wallpaper-1bd71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmvmbCO1ApUOPsczG7TO0v-e9M1pcT7rA',
    appId: '1:713380258131:ios:222664743a948cd7ee41a6',
    messagingSenderId: '713380258131',
    projectId: 'wallpaper-1bd71',
    storageBucket: 'wallpaper-1bd71.appspot.com',
    iosBundleId: 'com.demakk.wallpaper',
  );
}
